Imports System.Text.RegularExpressions
Imports ExcelDna.Integration
Imports Microsoft.Office.Interop.Excel

Public Class ProcessDecaySeries

    Public Function ClearBranches(ByRef gdcdci() As Collection, Optional Branches As Integer = maxBranches) As Boolean
        '* Usage:       Clears the collection data structures
        '* Input:       gdcdci() - array of Collection object
        '*              Branches - number of collections to clear in the array of
        '* Returns:     True if successful, otherwise False
        '* Author:      Backscatter enterprises
        '* Date:        12/25/2014

        Dim x As Integer
        Dim Msg As String

        On Error GoTo HandleErrors
        ClearBranches = False

        For x = 0 To Branches
            gdcdci(x) = Nothing
        Next x

        ClearBranches = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, vbCritical, "Error")
        End If

        ClearBranches = False

    End Function

#Disable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Public Function GetDecayChain(
    sParent As String, ByVal sTerminal As String,
    ByRef gdcdci() As Collection,
    Optional Instance As Integer = 1,
    Optional currBranch As Integer = 1,
    Optional nextBranch As Integer = 1,
    Optional ByRef pds As IReadOnlyList(Of DecaySeriesItem) = Nothing,
    Optional OptionalSortOrder As Integer = 1) As Boolean
#Enable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.
        '* Usage:       Gets decay chain from sParent to sTerminal including all branches
        '* Input:       sParent = starting member isotope
        '*              sTerminal = last member isotope
        '*              gdcdci() = an empty array of Collections of DecaySeriesItems
        '*              Instance = which recursion instance is this
        '*              currBranch = which member of the gdcdci() is being loaded
        '*              nextBranch = which member is next to be loaded
        '* Returns:     Nothing, but gdcdci() is fully loaded and ready for use
        '* Author:      Backscatter enterprises
        '* Date:        8/25/2023

        Dim Msg As String
        Dim x As Integer
        Dim y As Integer
        Dim z As Integer
        Dim bRsp As Boolean

        On Error GoTo 0

        sParent = UCase(sParent)
        sTerminal = UCase(sTerminal)

        If pds Is Nothing Then 'only load pds once per parent, then refer for each daughter in each branch
            pds = DecaySeriesRepository.GetAllList()
        End If

        'All Isotopes
        If sParent = "ALL" Then
            gdcdci(0) = DecaySeriesRepository.GetAll()
            GoTo ExitHere
        End If

        ' O(1) lookup of every position where sParent occurs, in ascending
        ' table order, instead of an O(n) scan over the full ~5,500-item
        ' table. The full ENSDF table (unlike the old 182-isotope table)
        ' has isotopes with more than two recorded decay modes - e.g.
        ' Bi-214 has three (to Po-214, Tl-210, and a direct branch to
        ' Pb-210) - so every occurrence beyond the first is a distinct
        ' alternate branch, not just the second.
        Dim parentIndices As IReadOnlyList(Of Integer) = DecaySeriesRepository.IndicesOf(sParent)

        If parentIndices.Count > 0 Then
            x = parentIndices(0) + 1 '1-based, to match the pds.Item(x)-style access below

            If (pds(x - 1).BranchingRatio <> 1.0#) And (sParent <> sTerminal) Then 'hit a branch point
                'Fork one branch per additional occurrence of sParent (parentIndices(1), (2), ...)
                Dim altIndex As Integer
                For altIndex = 1 To parentIndices.Count - 1
                    'find empty branch = nextBranch
                    For y = currBranch + 1 To maxBranches
                        If (gdcdci(y).Count = 0) And (y <> currBranch) Then
                            nextBranch = y
                            y = maxBranches 'abort loop
                        End If
                    Next y
                    'Copy everything from currBranch to nextBranch
                    For y = 1 To gdcdci(currBranch).Count
                        bRsp = AddDecayChainItem(gdcdci(currBranch).Item(y), gdcdci(nextBranch))
                        If Not bRsp Then
                            GoTo HandleErrors
                        End If

                    Next y

                    'Add this alternate occurrence of sParent to nextBranch
                    bRsp = AddDecayChainItem(pds(parentIndices(altIndex)), gdcdci(nextBranch))
                    If Not bRsp Then
                        GoTo HandleErrors
                    End If

                    'Follow daughter down nextBranch
                    bRsp = GetDecayChain(DirectCast(gdcdci(nextBranch).Item(gdcdci(nextBranch).Count).Daughter, String), sTerminal, gdcdci, Instance + 1, nextBranch, pds:=pds)
                    If Not bRsp Then GoTo HandleErrors
                Next altIndex
            End If

            'Load database info into collection for first parent
            bRsp = AddDecayChainItem(pds(x - 1), gdcdci(currBranch))
            If Not bRsp Then GoTo HandleErrors

            'Continue with first daughter
            If sParent <> sTerminal Then
                bRsp = GetDecayChain(pds(x - 1).Daughter, sTerminal, gdcdci, Instance + 1, currBranch, pds:=pds)
                If Not bRsp Then GoTo HandleErrors
            End If
        End If

        'AbortBranchSearch:

        If Instance > 1 Then GoTo ExitHere 'still working branches

        'Kill branches that do not terminate with sTerminal
        For x = 1 To maxBranches
            If gdcdci(x).Count > 0 Then 'trap empty gdcdci(x)
                bRsp = VerifyDecayChain(sParent, sTerminal, gdcdci(x))
                If Not bRsp Then 'did not verify - remove branch
                    For y = 1 To gdcdci(x).Count
                        gdcdci(x).Remove(1)
                    Next y
                End If
            End If
        Next x

        'Make branches contiguous
        bRsp = False 'flag for found an array to pull back
        For x = 1 To maxBranches - 1
            If gdcdci(x).Count = 0 Then 'it's empty
                For y = x To maxBranches - 1 'pull the next one back
                    For z = 1 To gdcdci(y + 1).Count
                        gdcdci(y).Add(gdcdci(y + 1).Item(z))
                        bRsp = True 'found one to pull back
                    Next z
                    For z = 1 To gdcdci(y + 1).Count
                        gdcdci(y + 1).Remove(1)
                    Next z
                Next y
            End If
            If bRsp Then
                x = 0
                bRsp = False 'reset to look for double empty array
            End If
        Next x

        'Populate array element zero with key to create unique isotope enumeration
        For x = 1 To maxBranches
            'If Not gdcdci(x) Is Nothing Then
            If gdcdci(x) IsNot Nothing Then
                For y = 1 To gdcdci(x).Count
                    On Error Resume Next
                    gdcdci(0).Add(gdcdci(x).Item(y), DirectCast(gdcdci(x).Item(y).Isotope, String))
                    On Error GoTo 0
                Next y
            End If
        Next x

        'Bubble sort gdcdci(0) on Isotope mass then name
        bRsp = BubbleSortCollection(gdcdci(0), OptionalSortOrder)
        If Not bRsp Then GoTo HandleErrors

ExitHere:
        GetDecayChain = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        GetDecayChain = False

    End Function

    Public Function GetDecaySeries() As Collection
        '* Usage:       Contains the database for isotopes
        '* Input:       Nothing
        '* Returns:     Collection of DecaySeriesItem for every isotope
        '*              in the database, in the original table order
        '* Author:      Backscatter enterprises
        '* Date:        12/24/2024
        '* Updated:     7/3/2026 - data moved out of hardcoded object
        '*              initializers and into the embedded
        '*              DecaySeriesData.json resource, loaded once and
        '*              cached by DecaySeriesRepository. See
        '*              DecaySeriesRepository.vb for the caching
        '*              contract (shared, read-only DecaySeriesItem
        '*              instances).

#Disable Warning IDE0002 ' Simplify Member Access
        Return DecaySeriesRepository.GetAll()
#Enable Warning IDE0002 ' Simplify Member Access

    End Function 'GetDecaySeries

    'GetDecayChain

    Public Function InitBranches(ByRef gdcdci() As Collection, Optional Branches As Integer = maxBranches) As Boolean
        '* Usage:       Initializes the collection data structure
        '* Input:       gdcdci() - array of Collection object
        '*              Branches - number of collections to initialize in the array of
        '* Returns:     True if successful, otherwise False
        '* Author:      Backscatter enterprises
        '* Date:        12/25/2014

        Dim x As Integer
        Dim Msg As String

        On Error GoTo HandleErrors
        InitBranches = False

        For x = 0 To Branches
            gdcdci(x) = New Collection
        Next x

        InitBranches = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, vbCritical, "Error")
        End If

        InitBranches = False

    End Function

#Disable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Public Function ListAll(<ExcelArgument(AllowReference:=True)> ByVal uRngVal As String) As Boolean
#Enable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.
        '* Usage:       Lists entire database starting at uRng
        '* Input:       uRng = Cell address
        '* Returns:     True if successful, else False
        '* Author:      Backscatter enterprises
        '* Date:        10/29/2016

        On Error GoTo HandleErrors

        Dim pds As IReadOnlyList(Of DecaySeriesItem)
        Dim x As Double
        Dim r As Double
        Dim c As Double
        Dim Msg As String
        Dim iRng As Range
        Dim iSheet As Worksheet
        Dim uSheet As String
        Dim uRng As String = ""
        Dim pattern As String = "\](\w*)'?!(.*)"
        Dim rRegex As New Regex(pattern)
        Dim m As Match = rRegex.Match(uRngVal)

        'Get Regex groups from match
        uSheet = m.Groups(1).ToString
        uRng = m.Groups(2).ToString

        'Create the ranges and worksheet
        iRng = DirectCast(iExcel.Range(uRng), Range)
        iSheet = DirectCast(iExcel.Worksheets(uSheet), Worksheet)
        r = Convert.ToInt32(iRng.Row)
        c = Convert.ToInt32(iRng.Column)

        'Write Headers
        iSheet.Cells(r, c) = "Isotope"
        iSheet.Cells(r, c + 1) = "Lambda (/s)"
        iSheet.Cells(r, c + 2) = "DCF68inhF1 (rem/uCi)"
        iSheet.Cells(r, c + 3) = "DCF68inhF5 (rem/uCi)"
        iSheet.Cells(r, c + 4) = "DCF68inhM1 (rem/uCi)"
        iSheet.Cells(r, c + 5) = "DCF68inhM5 (rem/uCi)"
        iSheet.Cells(r, c + 6) = "DCF68inhS1 (rem/uCi)"
        iSheet.Cells(r, c + 7) = "DCF68inhS5 (rem/uCi)"
        iSheet.Cells(r, c + 8) = "DCF68ing (rem/uCi)"
        iSheet.Cells(r, c + 9) = "DCF72inhF1 (rem/uCi)"
        iSheet.Cells(r, c + 10) = "DCF72inhM1 (rem/uCi)"
        iSheet.Cells(r, c + 11) = "DCF72inhS1"
        iSheet.Cells(r, c + 12) = "DCF72ing (rem/uCi)"
        iSheet.Cells(r, c + 13) = "A1 (TBq)"
        iSheet.Cells(r, c + 14) = "A2 (TBq)"
        iSheet.Cells(r, c + 15) = "Daughter"
        iSheet.Cells(r, c + 16) = "BR"
        r += 1 'increment to the next row

        pds = DecaySeriesRepository.GetAllList()

        For x = 1 To pds.Count
            Dim item As DecaySeriesItem = pds(CInt(x) - 1)
            iSheet.Cells(r + x - 1, c) = item.Isotope
            iSheet.Cells(r + x - 1, c + 1) = item.Lambda
            iSheet.Cells(r + x - 1, c + 2) = item.DCF68inhF1
            iSheet.Cells(r + x - 1, c + 3) = item.DCF68inhF5
            iSheet.Cells(r + x - 1, c + 4) = item.DCF68inhM1
            iSheet.Cells(r + x - 1, c + 5) = item.DCF68inhM5
            iSheet.Cells(r + x - 1, c + 6) = item.DCF68inhS1
            iSheet.Cells(r + x - 1, c + 7) = item.DCF68inhS5
            iSheet.Cells(r + x - 1, c + 8) = item.DCF68ing
            iSheet.Cells(r + x - 1, c + 9) = item.DCF72inhF1
            iSheet.Cells(r + x - 1, c + 10) = item.DCF72inhM1
            iSheet.Cells(r + x - 1, c + 11) = item.DCF72inhS1
            iSheet.Cells(r + x - 1, c + 12) = item.DCF72ing
            iSheet.Cells(r + x - 1, c + 13) = item.A1
            iSheet.Cells(r + x - 1, c + 14) = item.A2
            iSheet.Cells(r + x - 1, c + 15) = item.Daughter
            iSheet.Cells(r + x - 1, c + 16) = item.BranchingRatio
        Next x

        ListAll = True

        Exit Function

HandleErrors:

        If Err.Number = 1004 Or Err.Number = 9 Then
            Err.Clear()
            ListAll = True
            Exit Function
        End If

        If Err.Number <> 0 Then
            Msg = "List All Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        ListAll = False

    End Function

#Disable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.

    Public Function VerifyDecayChain(ByVal sParent As String, ByVal sTerminal As String, ByVal vdcdci As Collection) As Boolean
#Enable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.
        '* Usage:       Verifies that sParent is the first item and sTerminal is the last item
        '* Input:       sParent = starting member isotope
        '*              sTerminal = last member isotope
        '*              vdcdci = Collection of DecaySeriesItems
        '* Returns:     True if sParent is first and sTerminal is last OR sTerminal is END
        '* Author:      Backscatter enterprises
        '* Date:        12/25/2014

        Dim Msg As String

        If sParent = sTerminal Then
            VerifyDecayChain = True
            GoTo ExitHere
        Else
            VerifyDecayChain = False
        End If

        On Error GoTo HandleErrors

        sParent = UCase(sParent)
        sTerminal = UCase(sTerminal)

        If DirectCast(vdcdci.Item(1).Isotope, String) = sParent And
        (DirectCast(vdcdci.Item(vdcdci.Count).Isotope, String) = sTerminal Or sTerminal = "END") Then
            VerifyDecayChain = True
        End If

ExitHere:
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        VerifyDecayChain = False

    End Function 'VerifyDecayChain

    'InitBranches

    'ClearBranches

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Public Function VerifyIsotope(uIsotope As String) As Boolean
        '* Usage:       Verifies isotope is in Class
        '* Input:       uIsotope (e.g., CS-137)
        '* Returns:     True if successful, else False
        '* Author:      Backscatter enterprises
        '* Date:        7/31/2015
        '* Updated:     7/5/2026 - O(1) index lookup instead of an O(n)
        '*              scan over the full isotope table (see
        '*              DecaySeriesRepository.IndicesOf).

        VerifyIsotope = DecaySeriesRepository.IndicesOf(uIsotope).Count > 0

    End Function

    Private Shared Function AddDecayChainItem(fromDCI As Object, ByRef toDCI As Collection) As Boolean
        '* Usage:       Adds a decay chain item to specified collection
        '* Input:       dci is a collection of decay series items
        '* Returns:     True if successful, else False
        '* Author:      Backscatter enterprises
        '* Date:        12/25/2014

        Dim dsi As DecaySeriesItem
        Dim bRsp As Boolean
        Dim Msg As String

        On Error GoTo HandleErrors

        dsi = New DecaySeriesItem
        bRsp = LoadDecaySeriesItem(fromDCI, dsi)
        If Not bRsp Then GoTo HandleErrors
        toDCI.Add(dsi)

        dsi = Nothing

        AddDecayChainItem = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        AddDecayChainItem = False

    End Function

    Private Shared Function BubbleSortCollection(ByRef gdcdci As Collection, OptionalSortOrder As Integer) As Boolean
        '* Usage:       Sorts gdcdci by .Isotopoe descending mass, then alphabetic symbol
        '* Input:       gdcdci = collection of DecaySeriesItems
        '* Returns:     True sort is successful
        '* Author:      Backscatter enterprises
        '* Date:        12/25/2014

        Dim dsi As DecaySeriesItem
        Dim i As Integer
        Dim j As Integer
        Dim NoExchanges As Boolean
        Dim Msg As String
        Dim bRsp As Boolean

        ' Loop until no more "exchanges" are made.

        If OptionalSortOrder < 2 Or OptionalSortOrder > 3 Then GoTo ExitHere 'No Sort

        j = 2 '***Assert element 1 is primary parent and is in the correct order, alphabetical within decreasing mass
        If OptionalSortOrder = 2 Then j = 1 '***Assert element 1 must be sorted, alphabetical within increasing mass

        Do
            NoExchanges = True
            ' Loop through each element in the array.
            For i = j To gdcdci.Count - 1

                'Substitution when isotope1 is less than the isotope2 following
                '***Assert OptionalSortOrder = {2,3}
                If DSIKeyCompare(DirectCast(gdcdci.Item(i).Isotope, String), DirectCast(gdcdci.Item(i + 1).Isotope, String), OptionalSortOrder) Then
                    NoExchanges = False
                    dsi = New DecaySeriesItem
                    bRsp = LoadDecaySeriesItem(gdcdci.Item(i), dsi)
                    If Not bRsp Then GoTo HandleErrors
                    gdcdci.Remove(i)
                    If i < gdcdci.Count Then
                        gdcdci.Add(dsi, dsi.Isotope, gdcdci.Item(i + 1).Isotope)
                    Else
                        gdcdci.Add(dsi, dsi.Isotope)
                    End If
                End If

            Next i

        Loop While Not NoExchanges

ExitHere:
        BubbleSortCollection = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        BubbleSortCollection = False

    End Function 'BubbleSortCollection

    Private Shared Function DSIKeyCompare(a As String, b As String, Optional OptionalSortOrder As Double = 1) As Boolean
        '* Usage:       Compares the value of a to b for sorting
        '* Input:       a and b are gdcdci.Isotope strings
        '* Returns:     True if mass A < mass B
        '*              False if mass A = mass B AND sym A > sym B
        '* Author:      Backscatter enterprises
        '* Date:        12/25/2014

        '***Assert a<>b

        Dim massA As String
        Dim massB As String
        Dim symA As String
        Dim symB As String
        Dim x As Integer
        Dim Msg As String

        On Error GoTo HandleErrors

        'get mass
        x = InStr(1, a, "-")
        massA = Right(a, Len(a) - x)
        If Right(a, 1) = "M" Then
            massA = Left(massA, Len(massA) - 1) 'clip it
        End If
        x = InStr(1, b, "-")
        massB = Right(b, Len(b) - x)
        If Right(b, 1) = "M" Then
            massB = Left(massB, Len(massB) - 1) 'clip it
        End If

        If Val(massA) <> Val(massB) Then
            Select Case OptionalSortOrder
                Case 2
                    DSIKeyCompare = Val(massA) > Val(massB)
                Case 3
                    DSIKeyCompare = Val(massA) < Val(massB)
                Case Else
                    DSIKeyCompare = True
            End Select
            Exit Function
        End If

        '***Assert masses are equal
        'get symbols
        x = InStr(1, a, "-")
        symA = Left(a, x)
        If Right(a, 1) = "M" Then
            symA += "M"
        End If
        x = InStr(1, b, "-")
        symB = Left(b, x)
        If Right(b, 1) = "M" Then
            symB += "M"
        End If

        DSIKeyCompare = symA > symB
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        DSIKeyCompare = False

    End Function 'DSIKeyCompare

    'AddDecayChainItem

    Private Shared Function LoadDecaySeriesItem(fromDSI As Object, ByRef toDSI As DecaySeriesItem) As Boolean
        '* Usage:       Loads decay series item to specified collection
        '* Input:       dci is a collection of decay series items
        '* Returns:     True if successful, else False
        '* Author:      Backscatter enterprises
        '* Date:        7/19/2015

        Dim Msg As String

        On Error GoTo HandleError

        toDSI.Isotope = DirectCast(fromDSI.Isotope, String)
        toDSI.DCF68inhF1 = DirectCast(fromDSI.DCF68inhF1, Double)
        toDSI.DCF68inhF5 = DirectCast(fromDSI.DCF68inhF5, Double)
        toDSI.DCF68inhM1 = DirectCast(fromDSI.DCF68inhM1, Double)
        toDSI.DCF68inhM5 = DirectCast(fromDSI.DCF68inhM5, Double)
        toDSI.DCF68inhS1 = DirectCast(fromDSI.DCF68inhS1, Double)
        toDSI.DCF68inhS5 = DirectCast(fromDSI.DCF68inhS5, Double)
        toDSI.DCF68ing = DirectCast(fromDSI.DCF68ing, Double)
        toDSI.DCF72inhF1 = DirectCast(fromDSI.DCF72inhF1, Double)
        toDSI.DCF72inhM1 = DirectCast(fromDSI.DCF72inhM1, Double)
        toDSI.DCF72inhS1 = DirectCast(fromDSI.DCF72inhS1, Double)
        toDSI.DCF72ing = DirectCast(fromDSI.DCF72ing, Double)
        toDSI.A1 = DirectCast(fromDSI.A1, Double)
        toDSI.A2 = DirectCast(fromDSI.A2, Double)
        toDSI.Daughter = DirectCast(fromDSI.Daughter, String)
        toDSI.Lambda = DirectCast(fromDSI.Lambda, Double)
        toDSI.BranchingRatio = DirectCast(fromDSI.BranchingRatio, Double)

        LoadDecaySeriesItem = True
        Exit Function

HandleError:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        LoadDecaySeriesItem = False

    End Function 'LoadDecaySeriesItem

    'ListAll

    Private Shared Function ReferenceToRange(<ExcelArgument(AllowReference:=True)> xlref As Object) As Object
        Dim strAddress As String = DirectCast(XlCall.Excel(XlCall.xlfReftext, xlref, True), String)
        ReferenceToRange = ExcelDnaUtil.Application.Range(strAddress)
    End Function

End Class