Imports System.Text.RegularExpressions
Imports ExcelDna.Integration
Imports Microsoft.Office.Interop.Excel

' The decay-chain calculation engine behind most of RadToolzFunctions.vb's
' exported UDFs (AValue, DCF, EnumDecayChain, FGE, HalfLife, PECi, RadDecay,
' SpA all route through GetDecayChain). Not itself a UDF - callers new up a
' ProcessDecaySeries instance and drive it through InitBranches ->
' GetDecayChain -> (read cDC) -> ClearBranches.
'
' RECURRING PATTERN NOTE (applies throughout this file, not repeated per
' function below): most methods use the legacy VB6-style idiom of
' "On Error GoTo HandleErrors" plus assigning the return value to the
' function's own name (e.g. "ClearBranches = True") instead of Return/Try-
' Catch. This is legacy unstructured error handling - per
' section_29_stop_and_ask, modifying an existing On Error handler requires a
' Stop-and-Ask, so none of it has been touched here; only comments have been
' added. Two related idioms recur too: (1) many methods GoTo a HandleErrors
' label that both logs via MsgBox and sets the function's return value to
' False/an error string, so a caller only needs to check the boolean/Object
' result, never an exception; (2) gdcdci()/cDC() throughout this file and its
' callers is always a fixed-size array of DecayChainBranch (DDR-0006; a
' Collection-backed representation before that), one slot per decay-
' chain branch, sized to Constants.maxBranches and indexed from 1 (slot 0 is
' reserved for GetDecayChain's consolidated, deduplicated isotope list - see
' GetDecayChain below). Also scattered through this file are single-word
' comments like 'GetDecayChain or 'ListAll sitting after an unrelated
' End Function - these are leftover procedure-list bookmarks from an older
' editor/outlining convention, not documentation; preserved as harmless
' relics rather than removed, since deleting them is outside a comment-only
' pass.
Public Class ProcessDecaySeries

    ' DDR-0017: debounces ListAll's overwrite-confirmation guard against
    ' redundant re-invocations for the same target range that Excel issues
    ' in rapid succession (observed 2-3x on workbook open) - see ListAll
    ' below. A new ProcessDecaySeries instance is created per RTZParams
    ' call, so this state must be Shared to survive across those calls.
    Private Shared _lastListAllRangeKey As String
    Private Shared _lastListAllWriteUtc As DateTime

    ' DDR-0017 follow-up: a completed-write timestamp alone does not catch
    ' a REENTRANT call for the same range that arrives while an earlier
    ' invocation is still in flight (confirmed via diagnostic logging: two
    ' invocations landed at the identical millisecond, both reading
    ' _lastListAllRangeKey as unset, because neither had reached the
    ' post-write bookkeeping yet - consistent with MsgBox's modal message
    ' loop letting Excel re-enter ListAll before the first call returns).
    ' This tracks ranges currently being handled so a reentrant call can be
    ' detected immediately, before either the guard or the write runs.
    Private Shared _listAllInProgressKeys As New HashSet(Of String)

    ''' <summary>
    ''' Sets every branch slot from 0 to Branches (inclusive) to Nothing,
    ''' releasing the DecayChainBranch references. Pairs with InitBranches,
    ''' which allocates fresh DecayChainBranch objects into the same slots -
    ''' callers use InitBranches before a GetDecayChain call and
    ''' ClearBranches after, once the branch data has been read out (see
    ''' AValue/DCF/HalfLife/etc.'s ExitHere blocks in RadToolzFunctions.vb).
    ''' </summary>
    Public Function ClearBranches(ByRef gdcdci() As DecayChainBranch, Optional Branches As Integer = maxBranches) As Boolean
        '* Usage:       Clears the branch data structures
        '* Input:       gdcdci() - array of DecayChainBranch object
        '*              Branches - number of collections to clear in the array of
        '* Returns:     True if successful, otherwise False

        Dim x As Integer
        Dim Msg As String

        On Error GoTo HandleErrors
        ClearBranches = False

        For x = 0 To Branches
            gdcdci(x) = Nothing
        Next x

        ClearBranches = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, vbCritical, "Error")
        End If

        ClearBranches = False

    End Function

#Disable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Public Function GetDecayChain(
    sParent As String, ByVal sTerminal As String,
    ByRef gdcdci() As DecayChainBranch,
    Optional Instance As Integer = 1,
    Optional currBranch As Integer = 1,
    Optional nextBranch As Integer = 1,
    Optional ByRef pds As IReadOnlyList(Of DecaySeriesItem) = Nothing,
    Optional OptionalSortOrder As Integer = 1,
    Optional ByRef reachCache As Dictionary(Of String, Boolean) = Nothing) As Boolean
#Enable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.
        '* Usage:       Gets decay chain from sParent to sTerminal including all branches
        '* Input:       sParent = starting member isotope
        '*              sTerminal = last member isotope
        '*              gdcdci() = an empty array of DecayChainBranch objects, each holding DecaySeriesItems
        '*              Instance = which recursion instance is this
        '*              currBranch = which member of the gdcdci() is being loaded
        '*              nextBranch = which member is next to be loaded
        '* Returns:     Nothing, but gdcdci() is fully loaded and ready for use
        '* Notes:       sParent = "ALL" is a special case (used by RTZParams/
        '*              ListAll's data dump) that bypasses the chain-walk
        '*              entirely and dumps the full table into gdcdci(0).
        '*              sTerminal = "END" is the other sentinel value,
        '*              meaning "no specific terminal - keep every branch"
        '*              (see VerifyDecayChain and CanReachTerminal below,
        '*              both of which special-case it); EnumDecayChain is
        '*              the caller that passes it. Instance tracks
        '*              recursion depth within one branch/fork's own
        '*              daughter chain (not one counter per branch); once
        '*              a recursive call returns with Instance > 1 the
        '*              caller knows it is still mid-branch and skips the
        '*              branch-cleanup/sort work below (Instance > 1 GoTo
        '*              ExitHere), which only the outermost (Instance = 1)
        '*              call performs once the whole tree is built.
        '*              currBranch is the branch slot being extended by
        '*              this call; nextBranch (only meaningful inside the
        '*              fork loop) is the first unused slot found for a
        '*              newly forked branch. gdcdci(0) is reserved
        '*              throughout for the final deduplicated, sorted
        '*              isotope list built at the end of the outermost call
        '*              - never a branch in its own right.

        Dim Msg As String
        Dim x As Integer
        Dim y As Integer
        Dim z As Integer
        Dim bRsp As Boolean
        Dim foundSlot As Boolean

        On Error GoTo 0

        sParent = UCase(sParent)
        sTerminal = UCase(sTerminal)

        If pds Is Nothing Then 'only load pds once per parent, then refer for each daughter in each branch
            pds = DecaySeriesRepository.GetAllList()
        End If

        If reachCache Is Nothing Then 'scoped to this top-level call only - sTerminal is fixed for the whole call tree (DDR-0002)
            reachCache = New Dictionary(Of String, Boolean)(StringComparer.OrdinalIgnoreCase)
        End If

        'All Isotopes
        If sParent = "ALL" Then
            Dim allBranch As New DecayChainBranch()
            For Each dsi As DecaySeriesItem In DecaySeriesRepository.GetAllList()
                allBranch.Add(dsi)
            Next
            gdcdci(0) = allBranch
            GoTo ExitHere
        End If

        ' O(1) lookup of every position where sParent occurs, in ascending
        ' table order, instead of an O(n) scan over the full ~5,500-item
        ' table. The full ENSDF table (unlike the old 182-isotope table)
        ' has isotopes with more than two recorded decay modes - e.g.
        ' Bi-214 has three (to Po-214, Tl-210, and a direct branch to
        ' Pb-210) - so every occurrence beyond the first is a distinct
        ' alternate branch, not just the second.
        Dim parentIndices As IReadOnlyList(Of Integer) = DecaySeriesRepository.IndicesOf(sParent)

        If parentIndices.Count > 0 Then
            x = parentIndices(0) + 1 '1-based, to match the pds.Item(x)-style access below

            If (pds(x - 1).BranchingRatio <> 1.0#) And (sParent <> sTerminal) Then 'hit a branch point
                'Fork one branch per additional occurrence of sParent (parentIndices(1), (2), ...)
                Dim altIndex As Integer
                For altIndex = 1 To parentIndices.Count - 1
                    'Skip this occurrence entirely if its subtree can never reach sTerminal -
                    'avoids the prefix copy and the recursion beneath it for a branch that
                    'VerifyDecayChain would only prune away afterward anyway (DDR-0002).
                    If Not CanReachTerminal(pds(parentIndices(altIndex)).Daughter, sTerminal, pds, reachCache) Then
                        Continue For
                    End If

                    'find empty branch = nextBranch
                    foundSlot = False
                    For y = currBranch + 1 To maxBranches
                        If (gdcdci(y).Count = 0) And (y <> currBranch) Then
                            nextBranch = y
                            foundSlot = True
                            y = maxBranches 'abort loop
                        End If
                    Next y
                    'All branch slots are occupied - appending onto a stale nextBranch here
                    'would silently merge two unrelated branches' data (DEBT-0006) rather than
                    'raise an error, so treat exhaustion as a hard failure instead.
                    If Not foundSlot Then GoTo HandleErrors
                    'Copy everything from currBranch to nextBranch
                    For y = 1 To gdcdci(currBranch).Count
                        bRsp = AddDecayChainItem(gdcdci(currBranch).Item(y), gdcdci(nextBranch))
                        If Not bRsp Then
                            GoTo HandleErrors
                        End If

                    Next y

                    'Add this alternate occurrence of sParent to nextBranch
                    bRsp = AddDecayChainItem(pds(parentIndices(altIndex)), gdcdci(nextBranch))
                    If Not bRsp Then
                        GoTo HandleErrors
                    End If

                    'Follow daughter down nextBranch
                    bRsp = GetDecayChain(gdcdci(nextBranch).Item(gdcdci(nextBranch).Count).Daughter, sTerminal, gdcdci, Instance + 1, nextBranch, pds:=pds, reachCache:=reachCache)
                    If Not bRsp Then GoTo HandleErrors
                Next altIndex
            End If

            'Load database info into collection for first parent
            bRsp = AddDecayChainItem(pds(x - 1), gdcdci(currBranch))
            If Not bRsp Then GoTo HandleErrors

            'Continue with first daughter - same prune-before-recurse guard as the fork loop above (DDR-0002)
            If sParent <> sTerminal Then
                If CanReachTerminal(pds(x - 1).Daughter, sTerminal, pds, reachCache) Then
                    bRsp = GetDecayChain(pds(x - 1).Daughter, sTerminal, gdcdci, Instance + 1, currBranch, pds:=pds, reachCache:=reachCache)
                    If Not bRsp Then GoTo HandleErrors
                End If
            End If
        End If

        'AbortBranchSearch:

        If Instance > 1 Then GoTo ExitHere 'still working branches

        'Kill branches that do not terminate with sTerminal
        For x = 1 To maxBranches
            If gdcdci(x).Count > 0 Then 'trap empty gdcdci(x)
                bRsp = VerifyDecayChain(sParent, sTerminal, gdcdci(x))
                If Not bRsp Then 'did not verify - remove branch
                    For y = 1 To gdcdci(x).Count
                        gdcdci(x).Remove(1)
                    Next y
                End If
            End If
        Next x

        'Make branches contiguous
        bRsp = False 'flag for found an array to pull back
        For x = 1 To maxBranches - 1
            If gdcdci(x).Count = 0 Then 'it's empty
                For y = x To maxBranches - 1 'pull the next one back
                    For z = 1 To gdcdci(y + 1).Count
                        gdcdci(y).Add(gdcdci(y + 1).Item(z))
                        bRsp = True 'found one to pull back
                    Next z
                    For z = 1 To gdcdci(y + 1).Count
                        gdcdci(y + 1).Remove(1)
                    Next z
                Next y
            End If
            If bRsp Then
                x = 0
                bRsp = False 'reset to look for double empty array
            End If
        Next x

        'Populate array element zero with key to create unique isotope enumeration
        '* Updated:     7/6/2026 - a Collection.Add with a duplicate key throws,
        '*              and the same isotope legitimately repeats across branches
        '*              (e.g. Bi-214 forks three ways), so this used to rely on
        '*              letting that exception fail silently to drop repeats.
        '*              For a heavily-forked chain (e.g. U-238, ~70 branches) that
        '*              is hundreds of thrown-and-caught exceptions per call - the
        '*              dominant cost of GetDecayChain for any branching chain.
        '*              A HashSet membership check gives the same first-occurrence-
        '*              wins result with no exceptions on the normal path.
        Dim seenIsotopes As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase)
        For x = 1 To maxBranches
            'If Not gdcdci(x) Is Nothing Then
            If gdcdci(x) IsNot Nothing Then
                For y = 1 To gdcdci(x).Count
                    Dim candidate As DecaySeriesItem = gdcdci(x).Item(y)
                    Dim candidateIsotope As String = candidate.Isotope
                    If seenIsotopes.Add(candidateIsotope) Then
                        gdcdci(0).Add(candidate)
                    End If
                Next y
            End If
        Next x

        'Bubble sort gdcdci(0) on Isotope mass then name
        bRsp = BubbleSortCollection(gdcdci(0), OptionalSortOrder)
        If Not bRsp Then GoTo HandleErrors

ExitHere:
        GetDecayChain = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        GetDecayChain = False

    End Function

    Public Function GetDecaySeries() As Collection
        '* Usage:       Contains the database for isotopes
        '* Input:       Nothing
        '* Returns:     Collection of DecaySeriesItem for every isotope
        '*              in the database, in the original table order
        '* Updated:     7/3/2026 - data moved out of hardcoded object
        '*              initializers and into the embedded
        '*              DecaySeriesData.json resource, loaded once and
        '*              cached by DecaySeriesRepository. See
        '*              DecaySeriesRepository.vb for the caching
        '*              contract (shared, read-only DecaySeriesItem
        '*              instances).

#Disable Warning IDE0002 ' Simplify Member Access
        Return DecaySeriesRepository.GetAll()
#Enable Warning IDE0002 ' Simplify Member Access

    End Function 'GetDecaySeries

    'GetDecayChain

    ''' <summary>
    ''' Allocates a fresh, empty DecayChainBranch into every branch slot from
    ''' 0 to Branches (inclusive). Must be called before GetDecayChain, which
    ''' assumes every gdcdci(x) it might touch is a live DecayChainBranch (it
    ''' checks .Count, never IsNothing, on most slots) rather than Nothing.
    ''' </summary>
    Public Function InitBranches(ByRef gdcdci() As DecayChainBranch, Optional Branches As Integer = maxBranches) As Boolean
        '* Usage:       Initializes the branch data structure
        '* Input:       gdcdci() - array of DecayChainBranch object
        '*              Branches - number of branches to initialize in the array of
        '* Returns:     True if successful, otherwise False

        Dim x As Integer
        Dim Msg As String

        On Error GoTo HandleErrors
        InitBranches = False

        For x = 0 To Branches
            gdcdci(x) = New DecayChainBranch
        Next x

        InitBranches = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, vbCritical, "Error")
        End If

        InitBranches = False

    End Function

#Disable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Public Function ListAll(<ExcelArgument(AllowReference:=True)> ByVal uRngVal As String) As Boolean
#Enable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.
        '* Usage:       Lists entire database starting at uRng
        '* Input:       uRng = Cell address
        '* Returns:     True if successful, else False
        '* Notes:       uRngVal arrives as an already-fully-qualified Excel
        '*              reference string (e.g. "[Book1.xlsx]Sheet1!$A$1"),
        '*              produced by RTZParams via xlfReftext before calling
        '*              in here - this method does not itself resolve an
        '*              ExcelReference, it only parses the resulting text.
        '*              The regex below splits that string into the sheet
        '*              name (bracketed workbook name stripped) and the
        '*              range address, since iExcel.Worksheets()/.Range()
        '*              need them separately.

        On Error GoTo HandleErrors

        ' DDR-0017 follow-up: AllowReference:=True (required so RTZParams
        ' receives uRng as a genuine cell reference, not its resolved value)
        ' makes this function effectively volatile per Excel-DNA's own
        ' documented behavior (github.com/Excel-DNA/ExcelDna/issues/86) -
        ' Excel can dispatch two evaluations of the same formula back-to-back
        ' during workbook open, independent of anything this function does.
        ' A later-positioned in-progress check (keyed on the fully-resolved
        ' target range, after several COM calls to resolve Range/Worksheets)
        ' lost this race in testing: those COM calls gave a second
        ' near-simultaneous call enough of a window to also pass the check
        ' before the first call reached its own marker-set. uRngVal is the
        ' raw input string - no COM calls needed to read it - so checking
        ' and marking it as the very first statement closes that window to
        ' the minimum possible.
        Dim isReentrant As Boolean = _listAllInProgressKeys.Contains(uRngVal)

        If isReentrant Then
            ListAll = True
            Exit Function
        End If

        _listAllInProgressKeys.Add(uRngVal)

        Dim pds As IReadOnlyList(Of DecaySeriesItem)
        Dim x As Double
        Dim r As Double
        Dim c As Double
        Dim Msg As String
        Dim iRng As Range
        Dim iSheet As Worksheet
        Dim uSheet As String
        Dim uRng As String = ""
        ' Matches "]<sheetname>!<range>" - e.g. "]Sheet1!$A$1" out of
        ' "[Book1.xlsx]Sheet1!$A$1" - capturing the sheet name (an optional
        ' single-quoted name is tolerated but not itself captured) and the
        ' range address as the two groups read below.
        Dim pattern As String = "\](\w*)'?!(.*)"
        Dim rRegex As New Regex(pattern)
        Dim m As Match = rRegex.Match(uRngVal)

        'Get Regex groups from match
        uSheet = m.Groups(1).ToString
        uRng = m.Groups(2).ToString

        'Create the ranges and worksheet
        iRng = DirectCast(iExcel.Range(uRng), Range)
        iSheet = DirectCast(iExcel.Worksheets(uSheet), Worksheet)
        r = Convert.ToInt32(iRng.Row)
        c = Convert.ToInt32(iRng.Column)

        pds = DecaySeriesRepository.GetAllList()

        ' DEBT-0004: guard against silently overwriting a populated target range.
        Dim rowCount As Integer = 1 + pds.Count ' header row + one row per isotope
        Const colCount As Integer = 17
        Dim targetRange As Range = iSheet.Range(iSheet.Cells(r, c), iSheet.Cells(r + rowCount - 1, c + colCount - 1))

        ' DDR-0017: Excel can re-invoke RTZParams for this exact same range
        ' again shortly after a completed write (e.g. its own write counts
        ' as one of the "any change" triggers noted above) - without this,
        ' that re-invocation would independently re-prompt because the
        ' range still holds this function's own just-written data. Skip
        ' straight to success if we wrote this identical range moments ago.
        ' (The reentrancy case - two evaluations racing before either
        ' completes - is handled by the uRngVal-keyed check above; this
        ' timestamp debounce only needs to catch a genuinely-later repeat.)
        Dim rangeKey As String = targetRange.Address(External:=True)
        Dim debounceElapsed As TimeSpan = DateTime.UtcNow - _lastListAllWriteUtc
        Dim debounceMatch As Boolean = StrComp(rangeKey, _lastListAllRangeKey) = 0 AndAlso debounceElapsed < TimeSpan.FromSeconds(2)

        If debounceMatch Then
            _listAllInProgressKeys.Remove(uRngVal)
            ListAll = True
            Exit Function
        End If

        If iExcel.WorksheetFunction.CountA(targetRange) > 0 Then
            Dim confirmResult As MsgBoxResult = MsgBox(
                "The output range starting at " & targetRange.Address & " already contains data that will be overwritten. Continue?",
                MsgBoxStyle.Exclamation Or MsgBoxStyle.YesNo, "RTZParams")
            If confirmResult <> MsgBoxResult.Yes Then
                _listAllInProgressKeys.Remove(uRngVal)
                ListAll = False
                Exit Function
            End If
        End If

        'Write Headers
        iSheet.Cells(r, c) = "Isotope"
        iSheet.Cells(r, c + 1) = "Lambda (/s)"
        iSheet.Cells(r, c + 2) = "DCF68inhF1 (rem/uCi)"
        iSheet.Cells(r, c + 3) = "DCF68inhF5 (rem/uCi)"
        iSheet.Cells(r, c + 4) = "DCF68inhM1 (rem/uCi)"
        iSheet.Cells(r, c + 5) = "DCF68inhM5 (rem/uCi)"
        iSheet.Cells(r, c + 6) = "DCF68inhS1 (rem/uCi)"
        iSheet.Cells(r, c + 7) = "DCF68inhS5 (rem/uCi)"
        iSheet.Cells(r, c + 8) = "DCF68ing (rem/uCi)"
        iSheet.Cells(r, c + 9) = "DCF72inhF1 (rem/uCi)"
        iSheet.Cells(r, c + 10) = "DCF72inhM1 (rem/uCi)"
        iSheet.Cells(r, c + 11) = "DCF72inhS1"
        iSheet.Cells(r, c + 12) = "DCF72ing (rem/uCi)"
        iSheet.Cells(r, c + 13) = "A1 (TBq)"
        iSheet.Cells(r, c + 14) = "A2 (TBq)"
        iSheet.Cells(r, c + 15) = "Daughter"
        iSheet.Cells(r, c + 16) = "BR"
        r += 1 'increment to the next row

        For x = 1 To pds.Count
            Dim item As DecaySeriesItem = pds(CInt(x) - 1)
            iSheet.Cells(r + x - 1, c) = item.Isotope
            iSheet.Cells(r + x - 1, c + 1) = item.Lambda
            iSheet.Cells(r + x - 1, c + 2) = item.DCF68inhF1
            iSheet.Cells(r + x - 1, c + 3) = item.DCF68inhF5
            iSheet.Cells(r + x - 1, c + 4) = item.DCF68inhM1
            iSheet.Cells(r + x - 1, c + 5) = item.DCF68inhM5
            iSheet.Cells(r + x - 1, c + 6) = item.DCF68inhS1
            iSheet.Cells(r + x - 1, c + 7) = item.DCF68inhS5
            iSheet.Cells(r + x - 1, c + 8) = item.DCF68ing
            iSheet.Cells(r + x - 1, c + 9) = item.DCF72inhF1
            iSheet.Cells(r + x - 1, c + 10) = item.DCF72inhM1
            iSheet.Cells(r + x - 1, c + 11) = item.DCF72inhS1
            iSheet.Cells(r + x - 1, c + 12) = item.DCF72ing
            iSheet.Cells(r + x - 1, c + 13) = item.A1
            iSheet.Cells(r + x - 1, c + 14) = item.A2
            iSheet.Cells(r + x - 1, c + 15) = item.Daughter
            iSheet.Cells(r + x - 1, c + 16) = item.BranchingRatio
        Next x

        ' DDR-0017: record this write so a redundant re-invocation of this
        ' exact range within the debounce window (checked above) short-circuits.
        _lastListAllRangeKey = rangeKey
        _lastListAllWriteUtc = DateTime.UtcNow
        _listAllInProgressKeys.Remove(uRngVal)

        ListAll = True

        Exit Function

HandleErrors:

        ' DDR-0017 follow-up: uRngVal's own entry is safe to remove even if
        ' the error occurred before this function's own guard logic ran -
        ' the parameter itself is never Nothing (arrives as a fully-resolved
        ' reference string from RTZParams), and HashSet(Of String).Remove
        ' for a key that was never added is a safe no-op. This covers every
        ' error exit from this function without needing to touch the legacy
        ' On Error control flow itself (see section_29_stop_and_ask on
        ' modifying it).
        _listAllInProgressKeys.Remove(uRngVal)

        ' 1004 ("Application-defined or object-defined error", the generic COM
        ' automation failure Excel raises for a bad Range/Worksheets lookup)
        ' and 9 ("Subscript out of range") are treated as benign here rather
        ' than reported - both are swallowed and ListAll still reports
        ' success. This tolerates a caller-supplied uRngVal that does not
        ' resolve to a usable range/sheet (e.g. malformed reference text)
        ' without popping an error dialog; any other error still falls
        ' through to the MsgBox below.
        If Err.Number = 1004 Or Err.Number = 9 Then
            Err.Clear()
            ListAll = True
            Exit Function
        End If

        If Err.Number <> 0 Then
            Msg = "List All Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        ListAll = False

    End Function

#Disable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.

    Public Function VerifyDecayChain(ByVal sParent As String, ByVal sTerminal As String, ByVal vdcdci As DecayChainBranch) As Boolean
#Enable Warning IDE0081 ' 'ByVal' keyword is unnecessary and can be removed.
        '* Usage:       Verifies that sParent is the first item and sTerminal is the last item
        '* Input:       sParent = starting member isotope
        '*              sTerminal = last member isotope
        '*              vdcdci = DecayChainBranch of DecaySeriesItems
        '* Returns:     True if sParent is first and sTerminal is last OR sTerminal is END
        '* Notes:       Called once per built branch, after GetDecayChain's
        '*              recursion completes, to decide which branches
        '*              survive (see the "Kill branches that do not
        '*              terminate with sTerminal" loop in GetDecayChain).
        '*              "sTerminal = END" always passes (a branch is kept
        '*              regardless of what it actually ends on) - this is
        '*              the same sentinel rule CanReachTerminal mirrors for
        '*              its own pre-build pruning check, and the two must
        '*              stay consistent - if they disagreed, GetDecayChain
        '*              could prune a branch before building it that this
        '*              method would otherwise have kept, or vice versa.

        Dim Msg As String

        If sParent = sTerminal Then
            VerifyDecayChain = True
            GoTo ExitHere
        Else
            VerifyDecayChain = False
        End If

        On Error GoTo HandleErrors

        sParent = UCase(sParent)
        sTerminal = UCase(sTerminal)

        If vdcdci.Item(1).Isotope = sParent And
        (vdcdci.Item(vdcdci.Count).Isotope = sTerminal Or sTerminal = "END") Then
            VerifyDecayChain = True
        End If

ExitHere:
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        VerifyDecayChain = False

    End Function 'VerifyDecayChain

    'InitBranches

    'ClearBranches

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Public Function VerifyIsotope(uIsotope As String) As Boolean
        '* Usage:       Verifies isotope is in Class
        '* Input:       uIsotope (e.g., CS-137)
        '* Returns:     True if successful, else False
        '* Updated:     7/5/2026 - O(1) index lookup instead of an O(n)
        '*              scan over the full isotope table (see
        '*              DecaySeriesRepository.IndicesOf).

        VerifyIsotope = DecaySeriesRepository.IndicesOf(uIsotope).Count > 0

    End Function

    Private Shared Function AddDecayChainItem(fromDCI As DecaySeriesItem, ByRef toDCI As DecayChainBranch) As Boolean
        '* Usage:       Adds a decay chain item to specified branch
        '* Input:       dci is a branch of decay series items
        '* Returns:     True if successful, else False
        '* Notes:       fromDCI is passed both a DecaySeriesItem straight out
        '*              of the shared, cached pds table and (elsewhere, e.g.
        '*              the branch-contiguity fix-up loop above) an existing
        '*              branch item being re-copied; both are the same
        '*              concrete type (DDR-0006 - DecayChainBranch.Item
        '*              returns DecaySeriesItem directly, so no late binding
        '*              is involved either way). This defensive
        '*              copy-via-LoadDecaySeriesItem is what keeps every
        '*              caller from ever mutating a shared DecaySeriesItem
        '*              instance in place, per the read-only contract
        '*              documented on DecaySeriesRepository.GetAll/GetAllList.

        Dim dsi As DecaySeriesItem
        Dim bRsp As Boolean
        Dim Msg As String

        On Error GoTo HandleErrors

        dsi = New DecaySeriesItem
        bRsp = LoadDecaySeriesItem(fromDCI, dsi)
        If Not bRsp Then GoTo HandleErrors
        toDCI.Add(dsi)

        dsi = Nothing

        AddDecayChainItem = True
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        AddDecayChainItem = False

    End Function

    <CodeAnalysis.SuppressMessage("Style", "IDE0002:Simplify Member Access", Justification:="<Pending>")>
    Private Shared Function CanReachTerminal(isotope As String, sTerminal As String, pds As IReadOnlyList(Of DecaySeriesItem), cache As Dictionary(Of String, Boolean), Optional visiting As HashSet(Of String) = Nothing) As Boolean
        '* Usage:       Memoized, isotope-name-only reachability check used to
        '*              prune a GetDecayChain branch before it is built instead
        '*              of after. No DecaySeriesItem copies, no Collection use -
        '*              just isotope symbol comparisons over the shared table.
        '* Input:       isotope = isotope symbol to test reachability from
        '*              sTerminal = target isotope symbol, or "END" (always
        '*                          reachable, matching VerifyDecayChain's own
        '*                          "sTerminal = END" rule)
        '*              pds = full isotope table
        '*              cache = memoization map, scoped to one top-level
        '*                      GetDecayChain call (sTerminal is fixed for
        '*                      that whole call tree)
        '*              visiting = cycle guard; decay chains are acyclic
        '*                          today, but nothing upstream enforces
        '*                          that as an invariant
        '* Returns:     True if any path from isotope can reach sTerminal

        If sTerminal = "END" Then
            Return True
        End If

        If isotope = sTerminal Then
            Return True
        End If

        Dim cached As Boolean = False
        If cache.TryGetValue(isotope, cached) Then
            Return cached
        End If

        If visiting Is Nothing Then
            visiting = New HashSet(Of String)(StringComparer.OrdinalIgnoreCase)
        End If

        If visiting.Contains(isotope) Then
            Return False 'cycle guard: treat as not provably reachable via this path
        End If
#Disable Warning IDE0058 ' Expression value is never used
        visiting.Add(isotope)
#Enable Warning IDE0058 ' Expression value is never used

        Dim result As Boolean = False
        Dim occurrences As IReadOnlyList(Of Integer) = DecaySeriesRepository.IndicesOf(isotope)
        For Each occurrenceIndex As Integer In occurrences
            If CanReachTerminal(pds(occurrenceIndex).Daughter, sTerminal, pds, cache, visiting) Then
                result = True
                Exit For
            End If
        Next occurrenceIndex

#Disable Warning IDE0058 ' Expression value is never used
        visiting.Remove(isotope)
#Enable Warning IDE0058 ' Expression value is never used
        cache(isotope) = result

        Return result

    End Function 'CanReachTerminal

    Private Shared Function BubbleSortCollection(ByRef gdcdci As DecayChainBranch, OptionalSortOrder As Integer) As Boolean
        '* Usage:       Sorts gdcdci by .Isotopoe descending mass, then alphabetic symbol
        '* Input:       gdcdci = DecayChainBranch of DecaySeriesItems
        '* Returns:     True sort is successful
        '* Notes:       OptionalSortOrder: 1 = no sort (the default; this
        '*              function returns immediately without touching
        '*              gdcdci), 2 = ascending mass, 3 = descending mass -
        '*              see EnumDecayChain's own OptionalSortOrder argument,
        '*              which is threaded straight through GetDecayChain to
        '*              here. A classic bubble sort: repeated passes
        '*              swapping adjacent out-of-order pairs until a full
        '*              pass makes no swaps (NoExchanges stays True). A
        '*              "swap" here is a direct in-place exchange via
        '*              DecayChainBranch's Item(i) setter (DDR-0006) - O(1)
        '*              per swap, replacing the Collection-based remove-and-
        '*              reinsert-by-key dance this used to require (Collection
        '*              had no indexer-based Item(i) = value setter), which
        '*              was O(n) per swap on top of the O(n^2) comparisons
        '*              already inherent to bubble sort.

        Dim i As Integer
        Dim j As Integer
        Dim NoExchanges As Boolean

        ' Loop until no more "exchanges" are made.

        If OptionalSortOrder < 2 Or OptionalSortOrder > 3 Then GoTo ExitHere 'No Sort

        j = 2 '***Assert element 1 is primary parent and is in the correct order, alphabetical within decreasing mass
        If OptionalSortOrder = 2 Then j = 1 '***Assert element 1 must be sorted, alphabetical within increasing mass

        Do
            NoExchanges = True
            ' Loop through each element in the array.
            For i = j To gdcdci.Count - 1

                'Substitution when isotope1 is less than the isotope2 following
                '***Assert OptionalSortOrder = {2,3}
                If DSIKeyCompare(gdcdci.Item(i).Isotope, gdcdci.Item(i + 1).Isotope, OptionalSortOrder) Then
                    NoExchanges = False
                    Dim temp As DecaySeriesItem = gdcdci.Item(i)
                    gdcdci.Item(i) = gdcdci.Item(i + 1)
                    gdcdci.Item(i + 1) = temp
                End If

            Next i

        Loop While Not NoExchanges

ExitHere:
        BubbleSortCollection = True
        Exit Function

    End Function 'BubbleSortCollection

    Private Shared Function DSIKeyCompare(a As String, b As String, Optional OptionalSortOrder As Double = 1) As Boolean
        '* Usage:       Compares the value of a to b for sorting
        '* Input:       a and b are gdcdci.Isotope strings
        '* Returns:     True if mass A < mass B
        '*              False if mass A = mass B AND sym A > sym B
        '* Notes:       Isotope strings are always "<Symbol>-<Mass>", with
        '*              an optional trailing "M" marking a metastable state
        '*              (e.g. "TC-99M"). massA/massB pull the substring
        '*              after the "-" and strip a trailing "M" before Val()
        '*              converts it to a number, so metastable states sort
        '*              by the same mass as their ground state and are only
        '*              distinguished afterward by the symA/symB comparison
        '*              (which re-appends "M" so e.g. "TC-99M" sorts after
        '*              "TC-99"). The return value's meaning flips with
        '*              OptionalSortOrder (see the Select Case below) -
        '*              despite the fixed doc above, it is really "should a
        '*              and b swap" per the caller's requested direction,
        '*              not always literally "mass A < mass B".

        '***Assert a<>b

        Dim massA As String
        Dim massB As String
        Dim symA As String
        Dim symB As String
        Dim x As Integer
        Dim Msg As String

        On Error GoTo HandleErrors

        'get mass
        x = InStr(1, a, "-")
        massA = Right(a, Len(a) - x)
        If Right(a, 1) = "M" Then
            massA = Left(massA, Len(massA) - 1) 'clip it
        End If
        x = InStr(1, b, "-")
        massB = Right(b, Len(b) - x)
        If Right(b, 1) = "M" Then
            massB = Left(massB, Len(massB) - 1) 'clip it
        End If

        If Val(massA) <> Val(massB) Then
            Select Case OptionalSortOrder
                Case 2
                    DSIKeyCompare = Val(massA) > Val(massB)
                Case 3
                    DSIKeyCompare = Val(massA) < Val(massB)
                Case Else
                    DSIKeyCompare = True
            End Select
            Exit Function
        End If

        '***Assert masses are equal
        'get symbols
        x = InStr(1, a, "-")
        symA = Left(a, x)
        If Right(a, 1) = "M" Then
            symA += "M"
        End If
        x = InStr(1, b, "-")
        symB = Left(b, x)
        If Right(b, 1) = "M" Then
            symB += "M"
        End If

        DSIKeyCompare = symA > symB
        Exit Function

HandleErrors:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        DSIKeyCompare = False

    End Function 'DSIKeyCompare

    'AddDecayChainItem

    Private Shared Function LoadDecaySeriesItem(fromDSI As DecaySeriesItem, ByRef toDSI As DecaySeriesItem) As Boolean
        '* Usage:       Loads decay series item to specified collection
        '* Input:       dci is a collection of decay series items
        '* Returns:     True if successful, else False
        '* Notes:       Despite the name, this does not load anything from a
        '*              collection - it field-by-field copies fromDSI into
        '*              toDSI, a caller-owned DecaySeriesItem instance. Both
        '*              are DecaySeriesItem (DDR-0006; fromDSI was
        '*              previously typed Object for late-bound duck typing
        '*              against either a real DecaySeriesItem or a
        '*              Collection.Item(x) result - DecayChainBranch.Item
        '*              now always returns DecaySeriesItem directly, so that
        '*              is no longer needed). This is the one place that
        '*              performs the "copy properties into a new
        '*              DecaySeriesItem" step referenced by
        '*              DecaySeriesRepository's read-only contract - every
        '*              consumer that needs a modifiable DecaySeriesItem
        '*              goes through here rather than mutating a shared
        '*              cached instance.

        Dim Msg As String

        On Error GoTo HandleError

        toDSI.Isotope = fromDSI.Isotope
        toDSI.DCF68inhF1 = fromDSI.DCF68inhF1
        toDSI.DCF68inhF5 = fromDSI.DCF68inhF5
        toDSI.DCF68inhM1 = fromDSI.DCF68inhM1
        toDSI.DCF68inhM5 = fromDSI.DCF68inhM5
        toDSI.DCF68inhS1 = fromDSI.DCF68inhS1
        toDSI.DCF68inhS5 = fromDSI.DCF68inhS5
        toDSI.DCF68ing = fromDSI.DCF68ing
        toDSI.DCF72inhF1 = fromDSI.DCF72inhF1
        toDSI.DCF72inhM1 = fromDSI.DCF72inhM1
        toDSI.DCF72inhS1 = fromDSI.DCF72inhS1
        toDSI.DCF72ing = fromDSI.DCF72ing
        toDSI.A1 = fromDSI.A1
        toDSI.A2 = fromDSI.A2
        toDSI.Daughter = fromDSI.Daughter
        toDSI.Lambda = fromDSI.Lambda
        toDSI.BranchingRatio = fromDSI.BranchingRatio

        LoadDecaySeriesItem = True
        Exit Function

HandleError:
        If Err.Number <> 0 Then
            Msg = "Error # " & Str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl() & Chr(13) & Err.Description
            Dim msgBoxResult As Object = MsgBox(Msg, , "Error")
        End If

        LoadDecaySeriesItem = False

    End Function 'LoadDecaySeriesItem

    'ListAll

End Class