name: Build XLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore RadToolz.sln

    - name: Post-build steps for Excel-DNA 32-bit
      run: |
        msbuild /t:Build /p:Configuration=Release /p:Platform=x86 /p:OutputPath=Builds
        ExcelDnaPack.exe /Y Builds\RadToolz-AddIn.dna /O Builds\RadToolz-AddIn.xll

    - name: Post-build steps for Excel-DNA 64-bit
      run: |
        msbuild /t:Build /p:Configuration=Release /p:Platform=x64 /p:OutputPath=Builds
        ExcelDnaPack.exe /Y Builds\RadToolz-AddIn.dna /O Builds\RadToolz-AddIn64.xll

    - name: List Builds folder contents
      run: dir Builds
