name: Build and Package XLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU"

#    - name: Package XLL (32-bit)
#      run: |
#        $excelDnaPack = "${{ github.workspace }}\packages\ExcelDna.AddIn.1.8.0\tools\ExcelDnaPack.exe"
#        $dnaFile = "${{ github.workspace }}\RadToolz\bin\Release\RadToolz-AddIn.dna"
#        & $excelDnaPack $dnaFile /Y /O /XLL32

#    - name: Package XLL (64-bit)
#      run: |
#        $excelDnaPack = "${{ github.workspace }}\packages\ExcelDna.AddIn.1.8.0\tools\ExcelDnaPack.exe"
#        $dnaFile = "${{ github.workspace }}\RadToolz\bin\Release\RadToolz-AddIn64.dna"
#        & $excelDnaPack $dnaFile /Y /O /XLL64

    - name: Upload XLL binaries
      uses: actions/upload-artifact@v3
      with:
        name: xll-binaries
        path: |
          ${{ github.workspace }}\RadToolz\bin\Release\RadToolz-AddIn-packed.xll
          ${{ github.workspace }}\RadToolz\bin\Release\RadToolz-AddIn64-packed.xll


