name: Build and Package XLL v.3
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v4.02'

jobs:
  build_and_package:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up .NET Framework 4.8.1
    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    # Set up MSBuild
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore dependencies
    - name: Restore dependencies
      run: nuget restore

    # Build the project
    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Optimize=true /p:DebugType=none /p:DebugSymbols=false

    - name: List output directory contents
      run: dir ${{ github.workspace }}\Radtoolz\bin\Release

    - name: Set output paths
      run: |
        echo "XLL32_PATH=${{ github.workspace }}\Radtoolz\bin\Release\RadToolz-AddIn-packed.xll" >> $GITHUB_ENV
        echo "XLL64_PATH=${{ github.workspace }}\Radtoolz\bin\Release\RadToolz-AddIn64-packed.xll" >> $GITHUB_ENV

    - name:  Test XLL32 output path 
      run: echo ${{ env.XLL32_PATH }}

    - name:  Test XLL64 output path
      run:  echo ${{ env.XLL64_PATH }}
        
    - name: Upload XLL binaries
      uses: actions/upload-artifact@v4
      with:
        name: xll-binaries
        path: |
          ${{ env.XLL32_PATH }}
          ${{ env.XLL64_PATH }}



