name: Build and Package XLL v.4

on:
  workflow_dispatch:

jobs:
  build_package:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Optimize=false /p:DebugType=none /p:DebugSymbols=false

    - name: List output directory contents
      run: dir ${{ github.workspace }}\Radtoolz\bin\Release\RadToolz-AddIn*-packed.xll

    - name: Set output paths
      run: |
        echo "XLL32_PATH=${{ github.workspace }}\Radtoolz\bin\Release\RadToolz-AddIn-packed.xll" >> $GITHUB_ENV
        echo "XLL64_PATH=${{ github.workspace }}\Radtoolz\bin\Release\RadToolz-AddIn64-packed.xll" >> $GITHUB_ENV
      shell: cmd


    - name: Test XLL32 output path
      run: echo ${{ env.XLL32_PATH }}
      shell: cmd

    - name: Test XLL64 output path
      run: echo ${{ env.XLL64_PATH }}
      shell: cmd
        
    - name: Upload XLL binaries
      uses: actions/upload-artifact@v4
      with:
        name: xll-binaries
        path: |
          ${{ env.XLL32_PATH }}
          ${{ env.XLL64_PATH }}
