name: Build and Package XLL v.2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Optimize=false

    - name: List output directory contents
      run: dir ${{ github.workspace }}\bin\Release

    - name: Set output paths
      run: |
        echo "XLL32_PATH=${{ github.workspace }}\bin\Release\RadToolz-AddIn-packed.xll" >> $GITHUB_ENV
        echo "XLL64_PATH=${{ github.workspace }}\bin\Release\RadToolz-AddIn64-packed.xll" >> $GITHUB_ENV
        
    - name: Upload XLL binaries
      uses: actions/upload-artifact@v4
      with:
        name: xll-binaries
        path: |
          ${{ env.XLL32_PATH }}
          ${{ env.XLL64_PATH }}