name: Set and Display Environment Variable

on:
  workflow_dispatch:

jobs:
  set_and_display_variable:
    runs-on: windows-latest

    steps:

    - name: Display environment variable FOO
      run: echo $env:FOO
      env: 
        FOO: "test"
      
