name: Build and Release XLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Optimize=false

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v.4.01
        release_name: Release v.4.01
        draft: false
        prerelease: false

    - name: Upload XLL binaries
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn-packed.xll
        asset_name: RadToolz-AddIn-packed.xll
        asset_content_type: application/octet-stream

    - name: Upload XLL binaries (64-bit)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn64-packed.xll
        asset_name: RadToolz-AddIn64-packed.xll
        asset_content_type: application/octet-stream