name: Build and Release XLL v.6

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v4.01'

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up .NET Framework 4.8.1
    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    # Set up MSBuild
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore dependencies
    - name: Restore dependencies
      run: nuget restore

    # Build the project
    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Optimize=false /p:DebugType=none /p:DebugSymbols=false

    # Debug - List files in the output directory
    - name: Debug - List files
      run: ls -R ${{ github.workspace }}/RadToolz/bin/Release

    # Calculate SHA-256 hashes
    - name: Calculate SHA-256 hashes
      id: calculate_hashes
      run: |
        $hash1 = Get-FileHash ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn-packed.xll -Algorithm SHA256
        $hash2 = Get-FileHash ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn64-packed.xll -Algorithm SHA256
        "SHA256 Hashes" > sha256.txt
        "$($hash1.Hash)  RadToolz-AddIn-packed.xll" >> sha256.txt
        "$($hash2.Hash)  RadToolz-AddIn64-packed.xll" >> sha256.txt
        Get-Content sha256.txt

    # Install GitHub CLI
    - name: Install GitHub CLI
      run: |
        choco install gh -y

    # Create a new release
    - name: Create release
      id: create_release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $hashes = Get-Content sha256.txt -Raw
        gh release create ${{ github.event.inputs.version }} ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn-packed.xll ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn64-packed.xll --title "${{ github.event.inputs.version }}" --notes "$hashes"

    # List release assets
    - name: List release assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release view ${{ github.event.inputs.version }} --json assets --jq '.assets[].name'

    # Create attestation for RadToolz-AddIn-packed.xll
    - name: Create attestation for RadToolz-AddIn-packed.xll
      uses: actions/attest@v2.1.0
      with:
        subject-path: ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn-packed.xll
        subject-name: RadToolz-AddIn-packed.xll
        predicate-type: https://slsa.dev/provenance/v1
        predicate: |
          {
            "buildType": "https://github.com/radtoolz/RadToolz/.github/workflows/releasexllv6.yml@refs/heads/master",
            "builder": {
              "id": "https://github.com/radtoolz/RadToolz/.github/workflows/releasexllv6.yml@refs/heads/master"
            },
            "invocation": {
              "configSource": "https://github.com/radtoolz/RadToolz/.github/workflows/releasexllv6.yml@refs/heads/master",
              "parameters": {
                "version": "${{ github.event.inputs.version }}"
              },
              "environment": {
                "github_run_id": "${{ github.run_id }}",
                "github_run_attempt": "${{ github.run_attempt }}",
                "github_sha": "${{ github.sha }}",
                "github_ref": "${{ github.ref }}",
                "github_repository": "${{ github.repository }}",
                "github_actor": "${{ github.actor }}",
                "github_event_name": "${{ github.event_name }}",
                "github_event_path": "${{ github.event_path }}",
                "github_workspace": "${{ github.workspace }}"
              }
            }
          }
        push-to-registry: false
        show-summary: true

    # Create attestation for RadToolz-AddIn64-packed.xll
    - name: Create attestation for RadToolz-AddIn64-packed.xll
      uses: actions/attest@v2.1.0
      with:
        subject-path: ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn64-packed.xll
        subject-name: RadToolz-AddIn64-packed.xll
        predicate-type: https://slsa.dev/provenance/v1
        predicate: |
          {
            "buildType": "https://github.com/radtoolz/RadToolz/.github/workflows/releasexllv6.yml@refs/heads/master",
            "builder": {
              "id": "https://github.com/radtoolz/RadToolz/.github/workflows/releasexllv6.yml@refs/heads/master"
            },
            "invocation": {
              "configSource": "https://github.com/radtoolz/RadToolz/.github/workflows/releasexllv6.yml@refs/heads/master",
              "parameters": {
                "version": "${{ github.event.inputs.version }}"
              },
              "environment": {
                "github_run_id": "${{ github.run_id }}",
                "github_run_attempt": "${{ github.run_attempt }}",
                "github_sha": "${{ github.sha }}",
                "github_ref": "${{ github.ref }}",
                "github_repository": "${{ github.repository }}",
                "github_actor": "${{ github.actor }}",
                "github_event_name": "${{ github.event_name }}",
                "github_event_path": "${{ github.event_path }}",
                "github_workspace": "${{ github.workspace }}"
              }
            }
          }
        push-to-registry: false
        show-summary: true

