name: Build and Release XLL v.3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Framework 4.8.1
      run: |
        choco install netfx-4.8.1-devpack -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build project
      run: msbuild RadToolz.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Optimize=false

    - name: Debug - List files
      run: ls -R ${{ github.workspace }}/RadToolz/bin/Release

    - name: Install GitHub CLI
      run: |
        choco install gh -y

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create release
      id: create_release
      run: |
        gh release create v4.01 ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn-packed.xll ${{ github.workspace }}/RadToolz/bin/Release/RadToolz-AddIn64-packed.xll --title "Release v4.01" --notes "Release v4.01"

    - name: List release assets
      run: |
        gh release view v4.01 --json assets --jq '.assets[].name'